services:
  mosquitto:
    hostname: broker
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  gamelogic:
    build: ./gamelogic
    container_name: gamelogic
    restart: always
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=broker
      - MQTT_PORT=1883
      - MQTT_TOPIC=game
      - MQTT_CLIENT_ID=gamelogic
    volumes:
      - ./gamelogic:/usr/src/app
    ports:
      - 5000:5000
